use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use flate2::write::GzEncoder;
use flate2::Compression;
use sha2::{Digest, Sha256};

#[path = "src/webui/content_type.rs"]
mod content_type;

/// Emits `LLMMAN_VERSION`: the Cargo package version plus, when built from
/// a git checkout, the commit it was built from (e.g. "0.1.0 (a1b2c3d)").
/// Every nightly/CI build shares the same Cargo.toml version, so without
/// the commit suffix two different builds are indistinguishable to
/// `llmman --version` and the daemon's /api/version.
///
/// `LLMMAN_GIT_DESCRIBE`, if set, replaces the `git describe` output. CI
/// sets it to the bare commit hash after `packaging/version.sh --apply`
/// edits Cargo.toml/Cargo.lock, which would otherwise make every release
/// binary report `-dirty`.
fn emit_version() {
    let pkg = env::var("CARGO_PKG_VERSION").unwrap_or_default();
    println!("cargo:rerun-if-env-changed=LLMMAN_GIT_DESCRIBE");
    let describe = env::var("LLMMAN_GIT_DESCRIBE")
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .or_else(|| {
            Command::new("git")
                .args(["describe", "--always", "--dirty"])
                .output()
                .ok()
                .filter(|o| o.status.success())
                .and_then(|o| String::from_utf8(o.stdout).ok())
                .map(|s| s.trim().to_string())
                .filter(|s| !s.is_empty())
        });
    let version = match describe {
        Some(desc) => format!("{pkg} ({desc})"),
        None => pkg,
    };
    println!("cargo:rustc-env=LLMMAN_VERSION={version}");
    // `HEAD` only changes on a checkout/branch switch; an ordinary `git
    // commit` on the current branch instead updates `logs/HEAD` (the
    // reflog) — without watching that too, `--dirty`'s output (and so
    // LLMMAN_VERSION) can go stale across a commit, defeating
    // stale_daemon's version comparison in daemon.rs. Resolved via
    // `git rev-parse --git-path` rather than a hardcoded `.git/...` path
    // so this also reruns correctly from a linked worktree, where the
    // real HEAD/logs live under `.git/worktrees/<name>/` instead.
    for path in ["HEAD", "logs/HEAD"] {
        if let Some(resolved) = git_path(path) {
            println!("cargo:rerun-if-changed={}", resolved.display());
        }
    }
}

/// Resolves a path relative to the repo's git dir (e.g. `"HEAD"` or
/// `"logs/HEAD"`) via `git rev-parse --git-path`, so it's correct both for
/// a plain `.git` directory and a linked worktree's own `.git` file.
fn git_path(path: &str) -> Option<PathBuf> {
    Command::new("git")
        .args(["rev-parse", "--git-path", path])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| PathBuf::from(s.trim()))
}

fn main() {
    emit_version();
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Removed all Go shim CGO compilation logic, replacing with pure Rust dependencies.
    gzip_webui(&manifest_dir, &out_dir);
}

/// Gzip every file under `webui/` into `$OUT_DIR/webui_gz/` and write
/// `$OUT_DIR/webui_assets.rs`: a sorted `(path, content-type, etag, bytes)`
/// table src/webui/mod.rs `include!`s. Paths are relative to `webui/` with
/// `/` separators. Separate so the docs.rs early return can still run it.
fn gzip_webui(manifest_dir: &Path, out_dir: &Path) {
    let webui_src = manifest_dir.join("webui");
    let webui_out = out_dir.join("webui_gz");
    fs::create_dir_all(&webui_out).expect("create webui_gz dir");

    let mut files = Vec::new();
    collect_webui_files(&webui_src, &webui_src, &mut files);
    assert!(
        files.iter().any(|f| f == "index.html"),
        "webui/index.html is missing"
    );
    // Binary assets are not kept in the repository; see FETCHED_ASSETS.
    let fetched_dir = out_dir.join("webui_fetched");
    for asset in FETCHED_ASSETS {
        fetch_asset(asset, &fetched_dir);
        files.push(asset.path.to_string());
    }
    files.sort();
    files.dedup();

    let mut table = String::from(
        "/// Generated by build.rs: every file under `webui/`, gzipped:\n\
         /// `(path, content-type, etag, bytes)`.\n\
         pub static ASSETS: &[(&str, &str, &str, &[u8])] = &[\n",
    );
    for rel in &files {
        let content_type = content_type::for_path(rel)
            .unwrap_or_else(|| panic!("webui/{rel}: no content type for its extension; add one to src/webui/content_type.rs"));
        let src = if FETCHED_ASSETS.iter().any(|a| a.path == rel) {
            fetched_dir.join(rel)
        } else {
            webui_src.join(rel)
        };
        let dst = webui_out.join(format!("{}.gz", rel.replace('/', "__")));
        let data = fs::read(&src).unwrap_or_else(|e| panic!("read webui/{rel}: {e}"));
        let mut enc = GzEncoder::new(Vec::new(), Compression::best());
        enc.write_all(&data).expect("gzip write");
        let compressed = enc.finish().expect("gzip finish");
        fs::write(&dst, &compressed).unwrap_or_else(|e| panic!("write {}: {e}", dst.display()));
        table.push_str(&format!(
            "    ({rel:?}, {content_type:?}, {:?}, include_bytes!({:?})),\n",
            format!("\"{:016x}\"", fnv1a64(&compressed)),
            dst.to_str().expect("OUT_DIR is UTF-8"),
        ));
    }
    table.push_str("];\n");
    fs::write(out_dir.join("webui_assets.rs"), table).expect("write webui_assets.rs");

    println!("cargo:rerun-if-changed=webui/");
}

/// A web UI file kept out of the repository (no binaries in git) and
/// pulled from the `docs-assets` GitHub release at build time instead,
/// pinned by SHA-256.
struct FetchedAsset {
    /// Path under `webui/` it is served as.
    path: &'static str,
    url: &'static str,
    sha256: &'static str,
}

const FETCHED_ASSETS: &[FetchedAsset] = &[FetchedAsset {
    path: "manatee.png",
    url: "https://github.com/llmmanorg/llmman/releases/download/docs-assets/llmman-mark.png",
    sha256: "c6036711a349dc8f8b2b4405be90b342b477dbcf4a7d95eb7d05b42702a241d5",
}];

/// A 1x1 transparent PNG (Pillow output, verified to decode), served when
/// the download is impossible (docs.rs, offline builds).
const BLANK_PNG: &[u8] = &[
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4,
    0x89, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x44, 0x41, 0x54, 0x78, 0xda, 0x63, 0x60, 0x60, 0x60, 0x60,
    0x00, 0x00, 0x00, 0x05, 0x00, 0x01, 0x7a, 0xa8, 0x57, 0x50, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45,
    0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
];

/// Downloads `asset` into `dir` unless a copy with the right hash is
/// already there. `curl` rather than an HTTP crate: it is on every target
/// this builds on, and a build dependency would cost more compile time
/// than the file is worth. A failed download warns and writes the blank
/// PNG; a wrong hash is an error, since that is a changed upstream file.
fn fetch_asset(asset: &FetchedAsset, dir: &Path) {
    fs::create_dir_all(dir).expect("create webui_fetched dir");
    let dst = dir.join(asset.path);
    let hash_ok = |bytes: &[u8]| hex::encode(Sha256::digest(bytes)) == asset.sha256;
    if fs::read(&dst).is_ok_and(|b| hash_ok(&b)) {
        return;
    }
    let tmp = dst.with_extension("part");
    let fetched = Command::new("curl")
        .args(["-fsSL", "--retry", "3", "--max-time", "60", "-o"])
        .arg(&tmp)
        .arg(asset.url)
        .status()
        .is_ok_and(|s| s.success());
    let bytes = fetched.then(|| fs::read(&tmp).ok()).flatten();
    let _ = fs::remove_file(&tmp);
    match bytes {
        Some(bytes) if hash_ok(&bytes) => fs::write(&dst, bytes).expect("write fetched asset"),
        Some(_) => panic!(
            "{} does not match the sha256 pinned in build.rs ({}); update the pin if it changed on purpose",
            asset.url, asset.sha256
        ),
        None => {
            println!(
                "cargo:warning=could not download {} (offline?); the web UI will show no mark",
                asset.url
            );
            fs::write(&dst, BLANK_PNG).expect("write placeholder asset");
        }
    }
}

/// Regular files under `dir` as `/`-separated paths relative to `root`;
/// dotfiles (editor swap files, `.DS_Store`) are skipped.
fn collect_webui_files(root: &Path, dir: &Path, out: &mut Vec<String>) {
    let entries = fs::read_dir(dir).unwrap_or_else(|e| panic!("read {}: {e}", dir.display()));
    for entry in entries {
        let entry = entry.expect("read webui dir entry");
        let path = entry.path();
        if entry.file_name().to_string_lossy().starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect_webui_files(root, &path, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("under webui/")
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push(rel);
        }
    }
}

/// FNV-1a over the gzipped bytes, for the `ETag` header: no dependency,
/// and only "same file, same tag" matters.
fn fnv1a64(data: &[u8]) -> u64 {
    data.iter().fold(0xcbf2_9ce4_8422_2325u64, |h, b| {
        (h ^ u64::from(*b)).wrapping_mul(0x0000_0100_0000_01b3)
    })
}
